site_name: My Collections Novels
theme:
  name: null
  custom_dir: 'my_theme/'
nav:
  - Home: index.md
  - SClassIRised-001: SClassIRised-001.md
  - SClassIRised-002: SClassIRised-002.md
  - SClassIRised-003: SClassIRised-003.md
  - SClassIRised-004: SClassIRised-004.md
  - SClassIRised-005: SClassIRised-005.md
  - SClassIRised-006: SClassIRised-006.md
  - SClassIRised-007: SClassIRised-007.md
  - SClassIRised-008: SClassIRised-008.md
  - SClassIRised-009: SClassIRised-009.md
  - SClassIRised-010: SClassIRised-010.md
  - SClassIRised-011: SClassIRised-011.md
  - SClassIRised-012: SClassIRised-012.md
  - SClassIRised-013: SClassIRised-013.md
  - SClassIRised-014: SClassIRised-014.md
  - SClassIRised-015: SClassIRised-015.md
  - SClassIRised-016: SClassIRised-016.md
  - SClassIRised-017: SClassIRised-017.md
  - SClassIRised-018: SClassIRised-018.md
  - SClassIRised-019: SClassIRised-019.md
  - SClassIRised-020: SClassIRised-020.md
  - SClassIRised-021: SClassIRised-021.md
  - SClassIRised-022: SClassIRised-022.md
  - SClassIRised-023: SClassIRised-023.md
  - SClassIRised-024: SClassIRised-024.md
  - SClassIRised-025: SClassIRised-025.md
  - SClassIRised-026: SClassIRised-026.md
  - SClassIRised-027: SClassIRised-027.md
  - SClassIRised-028: SClassIRised-028.md
  - SClassIRised-029: SClassIRised-029.md
  - SClassIRised-030: SClassIRised-030.md
  - SClassIRised-031: SClassIRised-031.md
  - SClassIRised-032: SClassIRised-032.md
  - SClassIRised-033: SClassIRised-033.md
  - SClassIRised-034: SClassIRised-034.md
  - SClassIRised-035: SClassIRised-035.md
  - SClassIRised-036: SClassIRised-036.md
  - SClassIRised-037: SClassIRised-037.md
  - SClassIRised-038: SClassIRised-038.md
  - SClassIRised-039: SClassIRised-039.md
  - SClassIRised-040: SClassIRised-040.md
  - SClassIRised-041: SClassIRised-041.md
  - SClassIRised-042: SClassIRised-042.md
  - SClassIRised-043: SClassIRised-043.md
  - SClassIRised-044: SClassIRised-044.md
  - SClassIRised-045: SClassIRised-045.md
  - SClassIRised-046: SClassIRised-046.md
  - SClassIRised-047: SClassIRised-047.md
  - SClassIRised-048: SClassIRised-048.md
  - SClassIRised-049: SClassIRised-049.md
  - SClassIRised-050: SClassIRised-050.md
  - SClassIRised-051: SClassIRised-051.md
  - SClassIRised-052: SClassIRised-052.md
  - SClassIRised-053: SClassIRised-053.md
  - SClassIRised-054: SClassIRised-054.md
  - SClassIRised-055: SClassIRised-055.md
  - SClassIRised-056: SClassIRised-056.md
  - SClassIRised-057: SClassIRised-057.md
  - SClassIRised-058: SClassIRised-058.md
  - SClassIRised-059: SClassIRised-059.md
  - SClassIRised-060: SClassIRised-060.md
  - SClassIRised-061: SClassIRised-061.md
  - SClassIRised-062: SClassIRised-062.md
  - SClassIRised-063: SClassIRised-063.md
  - SClassIRised-064: SClassIRised-064.md
  - SClassIRised-065: SClassIRised-065.md
  - SClassIRised-066: SClassIRised-066.md
  - SClassIRised-067: SClassIRised-067.md
  - SClassIRised-068: SClassIRised-068.md
  - SClassIRised-069: SClassIRised-069.md
  - SClassIRised-070: SClassIRised-070.md
  - SClassIRised-071: SClassIRised-071.md
  - SClassIRised-072: SClassIRised-072.md
  - SClassIRised-073: SClassIRised-073.md
  - SClassIRised-074: SClassIRised-074.md
  - SClassIRised-075: SClassIRised-075.md
  - SClassIRised-076: SClassIRised-076.md
  - SClassIRised-077: SClassIRised-077.md
  - SClassIRised-078: SClassIRised-078.md
  - SClassIRised-079: SClassIRised-079.md
  - SClassIRised-080: SClassIRised-080.md
  - SClassIRised-081: SClassIRised-081.md
  - SClassIRised-082: SClassIRised-082.md
  - SClassIRised-083: SClassIRised-083.md
  - SClassIRised-084: SClassIRised-084.md
  - SClassIRised-085: SClassIRised-085.md
  - SClassIRised-086: SClassIRised-086.md
  - SClassIRised-087: SClassIRised-087.md
  - SClassIRised-088: SClassIRised-088.md
  - SClassIRised-089: SClassIRised-089.md
  - SClassIRised-090: SClassIRised-090.md
  - SClassIRised-091: SClassIRised-091.md
  - SClassIRised-092: SClassIRised-092.md
  - SClassIRised-093: SClassIRised-093.md
  - SClassIRised-094: SClassIRised-094.md
  - SClassIRised-095: SClassIRised-095.md
  - SClassIRised-096: SClassIRised-096.md
  - SClassIRised-097: SClassIRised-097.md
  - SClassIRised-098: SClassIRised-098.md
  - SClassIRised-099: SClassIRised-099.md
  - SClassIRised-100: SClassIRised-100.md
  - SClassIRised-101: SClassIRised-101.md
  - SClassIRised-102: SClassIRised-102.md
  - SClassIRised-103: SClassIRised-103.md
  - SClassIRised-104: SClassIRised-104.md
  - SClassIRised-105: SClassIRised-105.md
  - SClassIRised-106: SClassIRised-106.md
  - SClassIRised-107: SClassIRised-107.md
  - SClassIRised-108: SClassIRised-108.md
  - SClassIRised-109: SClassIRised-109.md
  - SClassIRised-110: SClassIRised-110.md
  - SClassIRised-111: SClassIRised-111.md
  - SClassIRised-112: SClassIRised-112.md
  - SClassIRised-113: SClassIRised-113.md
  - SClassIRised-114: SClassIRised-114.md
  - SClassIRised-115: SClassIRised-115.md
  - SClassIRised-116: SClassIRised-116.md
  - SClassIRised-117: SClassIRised-117.md
  - SClassIRised-118: SClassIRised-118.md
  - SClassIRised-119: SClassIRised-119.md
  - SClassIRised-120: SClassIRised-120.md
  - SClassIRised-121: SClassIRised-121.md
  - SClassIRised-122: SClassIRised-122.md
  - SClassIRised-123: SClassIRised-123.md
  - SClassIRised-124: SClassIRised-124.md
  - SClassIRised-125: SClassIRised-125.md
  - SClassIRised-126: SClassIRised-126.md
  - SClassIRised-127: SClassIRised-127.md
  - SClassIRised-128: SClassIRised-128.md
  - SClassIRised-129: SClassIRised-129.md
  - SClassIRised-130: SClassIRised-130.md
  - SClassIRised-131: SClassIRised-131.md
  - SClassIRised-132: SClassIRised-132.md
  - SClassIRised-133: SClassIRised-133.md
  - SClassIRised-134: SClassIRised-134.md
  - SClassIRised-135: SClassIRised-135.md
  - SClassIRised-136: SClassIRised-136.md
  - SClassIRised-137: SClassIRised-137.md
  - SClassIRised-138: SClassIRised-138.md
  - SClassIRised-139: SClassIRised-139.md
  - SClassIRised-140: SClassIRised-140.md
  - SClassIRised-141: SClassIRised-141.md
  - SClassIRised-142: SClassIRised-142.md
  - SClassIRised-143: SClassIRised-143.md
  - SClassIRised-144: SClassIRised-144.md
  - SClassIRised-145: SClassIRised-145.md
  - SClassIRised-146: SClassIRised-146.md
  - SClassIRised-147: SClassIRised-147.md
  - SClassIRised-148: SClassIRised-148.md
  - SClassIRised-149: SClassIRised-149.md
  - SClassIRised-150: SClassIRised-150.md
  - SClassIRised-151: SClassIRised-151.md
  - SClassIRised-152: SClassIRised-152.md
  - SClassIRised-153: SClassIRised-153.md
  - SClassIRised-154: SClassIRised-154.md
  - SClassIRised-155: SClassIRised-155.md
  - SClassIRised-156: SClassIRised-156.md
  - SClassIRised-157: SClassIRised-157.md
  - SClassIRised-158: SClassIRised-158.md
  - SClassIRised-159: SClassIRised-159.md
  - SClassIRised-160: SClassIRised-160.md
  - SClassIRised-161: SClassIRised-161.md
  - SClassIRised-162: SClassIRised-162.md
  - SClassIRised-163: SClassIRised-163.md
  - SClassIRised-164: SClassIRised-164.md
  - SClassIRised-165: SClassIRised-165.md
  - SClassIRised-166: SClassIRised-166.md
  - SClassIRised-167: SClassIRised-167.md
  - SClassIRised-168: SClassIRised-168.md
  - SClassIRised-169: SClassIRised-169.md
  - SClassIRised-170: SClassIRised-170.md
  - SClassIRised-171: SClassIRised-171.md
  - SClassIRised-172: SClassIRised-172.md
  - SClassIRised-173: SClassIRised-173.md
